# Generated by Django 5.0 on 2023-12-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('qty', models.PositiveIntegerField()),
                ('userId', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['userId'], name='cart_cartit_userId_f077de_idx'), models.Index(fields=['img'], name='cart_cartit_img_053b41_idx')],
            },
        ),
    ]
